const make = (cluster, track, hours, rows) => rows.map(([key, name, customHours, requires]) => ({ key, name, hours: customHours || hours, track, cluster, ...(requires ? { requires } : {}) }));

const humanities = make('Arts, Social Sciences & Humanities', 'Academic', 80, [
  ['citizenship_civic','Citizenship and Civic Engagement'],['creative_industries_vla','Creative Industries (Visual, Literary, Media, Applied & Traditional Art)'],['creative_industries_mdt','Creative Industries (Music, Dance & Theater)'],['creative_writing','Creative Writing'],['cultivating_filipino','Cultivating Filipino Identity Through the Arts'],['filipino_isports','Filipino sa Isports'],['filipino_sining','Filipino sa Sining at Disenyo'],['filipino_teknikal','Filipino sa Teknikal-Propesyonal'],['philosophy','Introduction to the Philosophy of the Human Person'],['leadership_arts','Leadership and Management in the Arts'],['malikhaing_pagsulat','Malikhaing Pagsulat'],['philippine_politics','Philippine Politics and Governance'],['social_sciences','The Social Sciences in Theory and Practice'],['wika_komunikasyon','Wika at Komunikasyon sa Akademikong Filipino']
]);
const business = make('Business & Entrepreneurship', 'Academic', 80, [['basic_accounting','Basic Accounting'],['business_finance','Business Finance and Income Taxation'],['contemporary_marketing','Contemporary Marketing and Business Economics'],['entrepreneurship_acad','Entrepreneurship'],['org_management','Introduction to Organization and Management']]);
const sports = make('Sports, Health & Wellness', 'Academic', 80, [['exercise_sports_prog','Exercise and Sports Programming'],['human_movement','Introduction to Human Movement'],['pe_fitness_rec','Physical Education (Fitness & Recreation)'],['pe_sports_dance','Physical Education (Sports & Dance)'],['safety_first_aid','Safety and First Aid'],['sports_activity_mgmt','Sports Activity Management'],['sports_coaching','Sports Coaching'],['sports_officiating','Sports Officiating']]);
const stem = make('Science, Technology, Engineering & Mathematics', 'Academic', 80, [['advanced_math','Advanced Mathematics 1-2',160],['biology_12','Biology 1-2',160],['chemistry_12','Chemistry 1-2',160],['database_management','Database Management'],['earth_space_science','Earth and Space Science 1-2',160],['empowerment_tech','Empowerment Technologies'],['finite_math','Finite Mathematics'],['data_analytics','Fundamentals of Data Analytics and Management'],['general_science_phys','General Science (Physical Science)'],['general_science_earth','General Science (Earth and Life Science)'],['pre_calculus','Pre-Calculus 1-2',160],['physics_12','Physics 1-2',160],['trigonometry','Trigonometry 1-2',160]]);
const field = make('Field Experience', 'Academic', 80, [['research_methods','Research Methods'],['design_innovation','Design and Innovation',160]]);
const ict = make('Information & Communication Technology', 'TechPro', 320, [['animation','Animation (NC II)'],['broadband_install','Broadband Installation (NC II)'],['comp_prog_java','Computer Programming (Java) (NC III)'],['comp_prog_oracle','Computer Programming (Oracle Database) (NC III)'],['css_nc2','Computer Systems Servicing (NC II)'],['contact_center','Contact Center Services (NC II)'],['illustration','Illustration (NC II)'],['prog_dotnet','Programming (.NET Technology) (NC III)'],['visual_graphic','Visual Graphic Design (NC III)']]);
const agriculture = make('Agriculture & Fishery Arts', 'TechPro', 320, [['agri_crops','Agricultural Crops Production (NC II)'],['agro_entrepreneurship','Agro-Entrepreneurship (NC II)'],['aquaculture','Aquaculture (NC II)'],['fish_capture','Fish Capture Operation (NC II)'],['food_processing','Food Processing (NC II)'],['organic_agri','Organic Agriculture Production (NC II)'],['poultry_prod','Poultry Production – Chicken (NC II)'],['ruminants_prod','Ruminants Production (NC II)'],['swine_prod','Swine Production (NC II)']]);
const consumer = make('Family & Consumer Science', 'TechPro', 320, [['aesthetic_services','Aesthetic Services (NC II)'],['bakery_ops','Bakery Operation (NC II)'],['caregiving_adult','Caregiving (Adult Care) (NC II)'],['caregiving_child','Caregiving (Child Care) (NC II)'],['events_mgmt','Events Management Services (NC III)'],['food_beverage','Food and Beverage Operation (NC II)'],['garment_artisanry','Garment Artisanry (NC II)'],['hairdressing','Hairdressing Services (NC II)'],['handicraft_weaving','Handicraft: Weaving (NC II)'],['hotel_frontoffice','Hotel Operations (Front Office Services) (NC II)'],['hotel_housekeeping','Hotel Operations (Housekeeping Services) (NC II)'],['kitchen_ops','Kitchen Operations (NC II)'],['tourism_services','Tourism Services (NC II)']]);
const industrial = make('Industrial Arts', 'TechPro', 320, [['automotive_engine','Automotive Servicing (Engine & Chassis) (NC II)'],['automotive_electrical','Automotive Servicing (Electrical) (NC II)'],['carpentry','Carpentry (NC I and NC II)'],['construction_masonry','Construction Operation (Masonry, Tiles & Plumbing)'],['aircon_commercial','Commercial Air-Conditioning Installation and Servicing (NC III)'],['aircon_domestic','Domestic Refrigeration and Air-Conditioning Servicing (NC II)'],['driving_automotive','Driving and Automotive Servicing'],['electrical_install','Electrical Installation Maintenance (NC II)'],['electronics_assembly','Electronics Product and Assembly Servicing (NC II)'],['welding','Manual Metal Arc Welding (NC II)'],['mechatronics','Mechatronics (NC II)'],['motorcycle_servicing','Motorcycle and Small Engine Servicing (NC II)'],['photovoltaic','Photovoltaic System Installation (NC II)'],['technical_drafting','Technical Drafting (NC II)']]);
const maritime = make('Maritime', 'TechPro', 320, [['marine_engineering','Marine Engineering at the Support Level'],['marine_transportation','Marine Transportation at the Support Level'],['ships_catering','Ships Catering Services (NC I)']]);
const immersion = make('Work Immersion', 'TechPro', 320, [['work_immersion','Work Immersion (Required for TechPro Track)']]);

export const catalog = [...humanities,...business,...sports,...stem,...field,...ict,...agriculture,...consumer,...industrial,...maritime,...immersion];
export const electives = {
  STEM: [...stem, ...field],
  ABM: [...business, ...field],
  HUMSS: [...humanities, ...sports, ...field],
  TVL: [...ict, ...agriculture, ...consumer, ...industrial, ...maritime, ...immersion],
  GAS: [...humanities, ...business, ...sports, ...stem, ...field]
};
export function validateElectives(strand, selected = []) {
  const available = electives[strand] || [];
  const keys = new Set(available.map(e => e.key));
  if (!Array.isArray(selected) || selected.length < 1 || selected.length > 10 || new Set(selected).size !== selected.length || selected.some(k => !keys.has(k))) return { valid:false, error:'Choose between 1 and 10 valid electives.' };
  const chosen = new Set(selected);
  for (const item of available) if (item.requires && chosen.has(item.key) && !chosen.has(item.requires)) return { valid:false, error:`${item.name} requires its prerequisite.` };
  return { valid:true };
}
